#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD

#define AUTO_SHIFT_REPEAT
#define USB_SUSPEND_WAKEUP_DELAY 1500
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define RGBLIGHT_SLEEP
#ifdef RGBLIGHT_ENABLE

    //#define RGBLIGHT_ANIMATIONS
	//#define RGBLIGHT_EFFECT_BREATHING
	#define RGBLIGHT_EFFECT_RAINBOW_MOOD
	//#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
	//#define RGBLIGHT_EFFECT_SNAKE
	//#define RGBLIGHT_EFFECT_KNIGHT
	//#define RGBLIGHT_EFFECT_CHRISTMAS
	//#define RGBLIGHT_EFFECT_STATIC_GRADIENT
	//#define RGBLIGHT_EFFECT_RGB_TEST
	//#define RGBLIGHT_EFFECT_ALTERNATING
	//#define RGBLIGHT_EFFECT_TWINKLE
#endif
